### ISSUE TITLE
Update React Native to 0.63.3

### ISSUE THREAD

**Issue by sanjeevyadavIT** [alexakasanjeev/react-native-boilerplate#13]
**Is your feature request related to a problem? Please describe.**
Upgrade React Native version to `0.63.3`

**Describe the solution you'd like**
Follow these steps to upgrade react native
1. Run the `upgrade` command

    ```
    react-native upgrade
    ```

    > Some files will not get upgraded, those files need to be changes manually
2. Open [React Native upgrade helper](https://react-native-community.github.io/upgrade-helper/) and choose 0.62.2 in left column and latest react native version(0.63.3) in right column
![react-native-upgrade](https://user-images.githubusercontent.com/13250741/66507532-f8458d80-eaec-11e9-9395-9fe51fea6357.png)
3. Files which were not changes automatically in Step 1, modified them manually using step 2
4. Run and test App on both Android & iOS

**Additional context**
Official React Native upgrade [guide](https://facebook.github.io/react-native/docs/0.60/upgrading)
To upgrade `ios/magento_react_native.xcodeproj/project.pbxproj` file follow this [guide](https://github.com/react-native-community/upgrade-helper/issues/47)

**TODO**
- [x] Upgrade react native from `0.59.5` to `^0.61.3` 
- [x] Test entire app for any case of failure

**Comment by DLambros91** [comment]
I could look into this if still needed.

**Comment by sanjeevyadavIT** [comment]
@DLambros91 Please go ahead

**Comment by phanlyhuynh** [comment]
@alexakasanjeev https://github.com/alexakasanjeev/react-native-boilerplate/pull/15 I upgraded react native version. Can you check for me? Thanks.

**Comment by sanjeevyadavIT** [comment]
@phanlyhuynh Thank you for your PR, I will most probably review your PR on Sunday, and will run the code once, to make sure everything is running & working properly.

Did you run the project, once you upgraded?
